package vista;

import controlador.LoginControlador;
import javax.swing.JOptionPane;

/**
 * HomeVista.java
 *
 * @author Miguel Alcantara
 * @version 1.0
 * @since 01/05/2020
 */
public class HomeVista extends javax.swing.JFrame {

    /**
     * Creates new form NewHomeVista
     */
    public HomeVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewHomeVistaTabbedPane = new javax.swing.JTabbedPane();
        libroPanel = new javax.swing.JPanel();
        isbnCheckBox = new javax.swing.JCheckBox();
        editorialLibroBox = new javax.swing.JTextField();
        __BUSCAR_LIBRO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        isbn1LibroBox = new javax.swing.JTextField();
        busquedaLibroBox = new javax.swing.JTextField();
        __NUEVO_LIBRO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        __GUARDAR_TABLA_LIBRO = new javax.swing.JButton();
        __MODIFICAR_LIBRO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        __CARGAR_TABLA_LIBRO = new javax.swing.JButton();
        __ELIMINAR_LIBRO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        __ANIADIR_NOTA_LIBRO = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        __VOLVER_LIBRO = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        __tabla_libros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        anioLibroFormatedBox = new javax.swing.JFormattedTextField();
        tituloLibroBox = new javax.swing.JTextField();
        nPaginasLibroFormatedBox = new javax.swing.JFormattedTextField();
        autorLibroBox = new javax.swing.JTextField();
        actualUsrLibro = new javax.swing.JLabel();
        __ACTUALIZAR_TABLA_LIBROS = new javax.swing.JButton();
        __LIMPIAR_LIBRO = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        isbn2LibroBox = new javax.swing.JTextField();
        __EXPORTAR_LIBRO = new javax.swing.JButton();
        articuloPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        __tabla_articulos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        anioArticuloFormatedBox = new javax.swing.JFormattedTextField();
        autorArticuloBox = new javax.swing.JTextField();
        mesArticuloFormatedBox = new javax.swing.JFormattedTextField();
        tituloArticuloBox = new javax.swing.JTextField();
        issnCheckBox = new javax.swing.JCheckBox();
        __BUSCAR_ARTICULO = new javax.swing.JButton();
        issn1ArticuloBox = new javax.swing.JTextField();
        busquedaArticuloBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        __GUARDAR_TABLA_ARTICULO = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __NUEVO_ARTICULO = new javax.swing.JButton();
        pagIniArticuloFormatedBox = new javax.swing.JFormattedTextField();
        __MODIFICAR_ARTICULO = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        __CARGAR_TABLA_ARTICULO = new javax.swing.JButton();
        revistaArticuloBox = new javax.swing.JTextField();
        __ELIMINAR_ARTICULO = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pagFinArticuloFormatedBox = new javax.swing.JFormattedTextField();
        __ANIADIR_NOTA_ARTICULO = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        __VOLVER_ARTICULO = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        actualUsrArticulo = new javax.swing.JLabel();
        __ACTUALIZAR_TABLA_ARTICULOS = new javax.swing.JButton();
        __LIMPIAR_ARTICULO = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        issn2ArticuloBox = new javax.swing.JTextField();
        __EXPORTAR_ARTICULO = new javax.swing.JButton();
        notaPanel = new javax.swing.JPanel();
        __CARGAR_TABLA_NOTA = new javax.swing.JButton();
        __GUARDAR_TABLA_NOTA = new javax.swing.JButton();
        temaNotaBox = new javax.swing.JTextField();
        __ELIMINAR_NOTA = new javax.swing.JButton();
        __MODIFICAR_NOTA = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        idNotaBox = new javax.swing.JFormattedTextField();
        __VOLVER_NOTA = new javax.swing.JButton();
        isbnNotaBox = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        __tabla_notas = new javax.swing.JTable();
        issnNotaBox = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        __BUSCAR_NOTA = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        busquedaNotaBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoNotaArea = new javax.swing.JTextArea();
        actualUsrNota = new javax.swing.JLabel();
        __ACTUALIZAR_TABLA_NOTAS = new javax.swing.JButton();
        __LIMPIAR_NOTA = new javax.swing.JButton();
        __EXPORTAR_NOTA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GRB");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        __BUSCAR_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __BUSCAR_LIBRO.setText("Buscar");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("LIBROS");

        __NUEVO_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __NUEVO_LIBRO.setText("Nuevo libro");

        jLabel2.setText("ISBN");

        __GUARDAR_TABLA_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __GUARDAR_TABLA_LIBRO.setText("Guardar tabla");

        __MODIFICAR_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __MODIFICAR_LIBRO.setText("Modificar libro");

        jLabel3.setText("Titulo");

        __CARGAR_TABLA_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __CARGAR_TABLA_LIBRO.setText("Cargar tabla");

        __ELIMINAR_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __ELIMINAR_LIBRO.setText("Eliminar libro");

        jLabel4.setText("Autor");

        __ANIADIR_NOTA_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __ANIADIR_NOTA_LIBRO.setText("Añadir nota");

        jLabel5.setText("Editorial");

        __VOLVER_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __VOLVER_LIBRO.setText("Cerrar sesion");

        jLabel6.setText("Año");

        __tabla_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(__tabla_libros);

        jLabel7.setText("Nº Pags");

        anioLibroFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        nPaginasLibroFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        actualUsrLibro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        actualUsrLibro.setForeground(new java.awt.Color(153, 153, 153));
        actualUsrLibro.setText("Usuario: "+LoginControlador.user.getNombre());

        __ACTUALIZAR_TABLA_LIBROS.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        __ACTUALIZAR_TABLA_LIBROS.setText("Actualizar");

        __LIMPIAR_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __LIMPIAR_LIBRO.setText("Limpiar campos");

        jLabel19.setText("-");

        __EXPORTAR_LIBRO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __EXPORTAR_LIBRO.setText("Exportar datos");

        javax.swing.GroupLayout libroPanelLayout = new javax.swing.GroupLayout(libroPanel);
        libroPanel.setLayout(libroPanelLayout);
        libroPanelLayout.setHorizontalGroup(
            libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroPanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1))
            .addGroup(libroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(__VOLVER_LIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busquedaLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(__BUSCAR_LIBRO))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroPanelLayout.createSequentialGroup()
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libroPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(__LIMPIAR_LIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libroPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actualUsrLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libroPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(isbnCheckBox))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libroPanelLayout.createSequentialGroup()
                                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(__NUEVO_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__MODIFICAR_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__ELIMINAR_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__ANIADIR_NOTA_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__EXPORTAR_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroPanelLayout.createSequentialGroup()
                        .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(autorLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anioLibroFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(libroPanelLayout.createSequentialGroup()
                                .addComponent(isbn1LibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isbn2LibroBox)))
                        .addGap(46, 46, 46)
                        .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloLibroBox)
                            .addComponent(editorialLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nPaginasLibroFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(libroPanelLayout.createSequentialGroup()
                        .addComponent(__ACTUALIZAR_TABLA_LIBROS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(__GUARDAR_TABLA_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(__CARGAR_TABLA_LIBRO))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        libroPanelLayout.setVerticalGroup(
            libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(actualUsrLibro)
                .addGap(18, 18, 18)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(libroPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__ACTUALIZAR_TABLA_LIBROS)
                            .addComponent(__GUARDAR_TABLA_LIBRO)
                            .addComponent(__CARGAR_TABLA_LIBRO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(libroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(isbnCheckBox)
                                    .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(isbn1LibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19)
                                        .addComponent(isbn2LibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(libroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(libroPanelLayout.createSequentialGroup()
                        .addComponent(__NUEVO_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__MODIFICAR_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__ELIMINAR_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__ANIADIR_NOTA_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__EXPORTAR_LIBRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__LIMPIAR_LIBRO)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editorialLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autorLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addGroup(libroPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anioLibroFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nPaginasLibroFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(libroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__VOLVER_LIBRO)
                    .addComponent(__BUSCAR_LIBRO)
                    .addComponent(busquedaLibroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NewHomeVistaTabbedPane.addTab("Libros", libroPanel);

        __tabla_articulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(__tabla_articulos);

        jLabel8.setText("Mes");

        anioArticuloFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        mesArticuloFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        __BUSCAR_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __BUSCAR_ARTICULO.setText("Buscar");

        jLabel9.setText("ISSN");

        __GUARDAR_TABLA_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __GUARDAR_TABLA_ARTICULO.setText("Guardar tabla");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText("ARTICULOS");

        jLabel11.setText("Autor");

        __NUEVO_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __NUEVO_ARTICULO.setText("Nuevo articulo");

        pagIniArticuloFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        __MODIFICAR_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __MODIFICAR_ARTICULO.setText("Modificar articulo");

        jLabel12.setText("Revista");

        __CARGAR_TABLA_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __CARGAR_TABLA_ARTICULO.setText("Cargar tabla");

        __ELIMINAR_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __ELIMINAR_ARTICULO.setText("Eliminar articulo");

        jLabel13.setText("Pag inicio");

        jLabel14.setText("Titulo");

        pagFinArticuloFormatedBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        __ANIADIR_NOTA_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __ANIADIR_NOTA_ARTICULO.setText("Añadir nota");

        jLabel15.setText("Pag fin");

        __VOLVER_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __VOLVER_ARTICULO.setText("Cerrar sesion");

        jLabel16.setText("Año");

        actualUsrArticulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        actualUsrArticulo.setForeground(new java.awt.Color(153, 153, 153));
        actualUsrArticulo.setText("Usuario: "+LoginControlador.user.getNombre());

        __ACTUALIZAR_TABLA_ARTICULOS.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        __ACTUALIZAR_TABLA_ARTICULOS.setText("Actualizar");

        __LIMPIAR_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __LIMPIAR_ARTICULO.setText("Limpiar campos");

        jLabel23.setText("-");

        __EXPORTAR_ARTICULO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __EXPORTAR_ARTICULO.setText("Exportar datos");

        javax.swing.GroupLayout articuloPanelLayout = new javax.swing.GroupLayout(articuloPanel);
        articuloPanel.setLayout(articuloPanelLayout);
        articuloPanelLayout.setHorizontalGroup(
            articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(articuloPanelLayout.createSequentialGroup()
                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(articuloPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel10))
                    .addGroup(articuloPanelLayout.createSequentialGroup()
                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(articuloPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(actualUsrArticulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(__VOLVER_ARTICULO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(__ANIADIR_NOTA_ARTICULO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(__MODIFICAR_ARTICULO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(__ELIMINAR_ARTICULO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(__NUEVO_ARTICULO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(issnCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(__LIMPIAR_ARTICULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(__EXPORTAR_ARTICULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(articuloPanelLayout.createSequentialGroup()
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(articuloPanelLayout.createSequentialGroup()
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(anioArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(mesArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tituloArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, articuloPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(129, 129, 129))
                                        .addGroup(articuloPanelLayout.createSequentialGroup()
                                            .addComponent(issn1ArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(issn2ArticuloBox)))
                                    .addComponent(jLabel9))
                                .addGap(45, 45, 45)
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(articuloPanelLayout.createSequentialGroup()
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(pagIniArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(pagFinArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 101, Short.MAX_VALUE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(autorArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(revistaArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(articuloPanelLayout.createSequentialGroup()
                                        .addComponent(__ACTUALIZAR_TABLA_ARTICULOS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__GUARDAR_TABLA_ARTICULO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__CARGAR_TABLA_ARTICULO))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(articuloPanelLayout.createSequentialGroup()
                                    .addComponent(busquedaArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(__BUSCAR_ARTICULO))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        articuloPanelLayout.setVerticalGroup(
            articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(articuloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(actualUsrArticulo)
                .addGap(18, 18, 18)
                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(articuloPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__GUARDAR_TABLA_ARTICULO)
                            .addComponent(__CARGAR_TABLA_ARTICULO)
                            .addComponent(__ACTUALIZAR_TABLA_ARTICULOS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(articuloPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autorArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revistaArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(articuloPanelLayout.createSequentialGroup()
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(issnCheckBox)
                                    .addGroup(articuloPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(issn1ArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23)
                                            .addComponent(issn2ArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(articuloPanelLayout.createSequentialGroup()
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pagIniArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagFinArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, articuloPanelLayout.createSequentialGroup()
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(anioArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mesArticuloFormatedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(articuloPanelLayout.createSequentialGroup()
                        .addComponent(__NUEVO_ARTICULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__MODIFICAR_ARTICULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__ELIMINAR_ARTICULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__ANIADIR_NOTA_ARTICULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__EXPORTAR_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__LIMPIAR_ARTICULO)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(articuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__VOLVER_ARTICULO)
                    .addComponent(busquedaArticuloBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__BUSCAR_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NewHomeVistaTabbedPane.addTab("Articulos", articuloPanel);

        __CARGAR_TABLA_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __CARGAR_TABLA_NOTA.setText("Cargar tabla");

        __GUARDAR_TABLA_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __GUARDAR_TABLA_NOTA.setText("Guardar tabla");

        __ELIMINAR_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __ELIMINAR_NOTA.setText("Eliminar nota");

        __MODIFICAR_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __MODIFICAR_NOTA.setText("Modificar nota");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setText("NOTAS");

        idNotaBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        idNotaBox.setEnabled(false);

        __VOLVER_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __VOLVER_NOTA.setText("Cerrar sesion");

        isbnNotaBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        isbnNotaBox.setEnabled(false);

        __tabla_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        __tabla_notas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        __tabla_notas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(__tabla_notas);

        issnNotaBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        issnNotaBox.setEnabled(false);

        jLabel18.setText("Libro");

        jLabel20.setText("Articulo");

        jLabel21.setText("Tema");

        __BUSCAR_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __BUSCAR_NOTA.setText("Buscar");

        jLabel22.setText("Contenido");

        contenidoNotaArea.setColumns(20);
        contenidoNotaArea.setRows(5);
        jScrollPane1.setViewportView(contenidoNotaArea);

        actualUsrNota.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        actualUsrNota.setForeground(new java.awt.Color(153, 153, 153));
        actualUsrNota.setText("Usuario: "+LoginControlador.user.getNombre());

        __ACTUALIZAR_TABLA_NOTAS.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        __ACTUALIZAR_TABLA_NOTAS.setText("Actualizar");

        __LIMPIAR_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __LIMPIAR_NOTA.setText("Limpiar campos");

        __EXPORTAR_NOTA.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        __EXPORTAR_NOTA.setText("Exportar datos");

        javax.swing.GroupLayout notaPanelLayout = new javax.swing.GroupLayout(notaPanel);
        notaPanel.setLayout(notaPanelLayout);
        notaPanelLayout.setHorizontalGroup(
            notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notaPanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(notaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(notaPanelLayout.createSequentialGroup()
                                .addComponent(__VOLVER_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(busquedaNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(__BUSCAR_NOTA))
                            .addGroup(notaPanelLayout.createSequentialGroup()
                                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(__MODIFICAR_NOTA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__ELIMINAR_NOTA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__LIMPIAR_NOTA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(__EXPORTAR_NOTA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(actualUsrNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(notaPanelLayout.createSequentialGroup()
                                        .addComponent(__ACTUALIZAR_TABLA_NOTAS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__GUARDAR_TABLA_NOTA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__CARGAR_TABLA_NOTA)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isbnNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issnNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(notaPanelLayout.createSequentialGroup()
                                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temaNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(85, 85, 85))
        );
        notaPanelLayout.setVerticalGroup(
            notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(actualUsrNota)
                .addGap(18, 18, 18)
                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addComponent(__MODIFICAR_NOTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__ELIMINAR_NOTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__EXPORTAR_NOTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(__LIMPIAR_NOTA))
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(__CARGAR_TABLA_NOTA)
                            .addComponent(__GUARDAR_TABLA_NOTA)
                            .addComponent(__ACTUALIZAR_TABLA_NOTAS))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(idNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issnNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isbnNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(notaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temaNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(notaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__VOLVER_NOTA)
                    .addComponent(busquedaNotaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__BUSCAR_NOTA))
                .addContainerGap())
        );

        NewHomeVistaTabbedPane.addTab("Notas", notaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewHomeVistaTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewHomeVistaTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Se pide una confirmación antes de finalizar el programa
        int option = JOptionPane.showConfirmDialog(null,
                "¿Estás seguro de que quieres cerrar la aplicacion?",
                "Confirmacion de cierre",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane NewHomeVistaTabbedPane;
    public javax.swing.JButton __ACTUALIZAR_TABLA_ARTICULOS;
    public javax.swing.JButton __ACTUALIZAR_TABLA_LIBROS;
    public javax.swing.JButton __ACTUALIZAR_TABLA_NOTAS;
    public javax.swing.JButton __ANIADIR_NOTA_ARTICULO;
    public javax.swing.JButton __ANIADIR_NOTA_LIBRO;
    public javax.swing.JButton __BUSCAR_ARTICULO;
    public javax.swing.JButton __BUSCAR_LIBRO;
    public javax.swing.JButton __BUSCAR_NOTA;
    public javax.swing.JButton __CARGAR_TABLA_ARTICULO;
    public javax.swing.JButton __CARGAR_TABLA_LIBRO;
    public javax.swing.JButton __CARGAR_TABLA_NOTA;
    public javax.swing.JButton __ELIMINAR_ARTICULO;
    public javax.swing.JButton __ELIMINAR_LIBRO;
    public javax.swing.JButton __ELIMINAR_NOTA;
    public javax.swing.JButton __EXPORTAR_ARTICULO;
    public javax.swing.JButton __EXPORTAR_LIBRO;
    public javax.swing.JButton __EXPORTAR_NOTA;
    public javax.swing.JButton __GUARDAR_TABLA_ARTICULO;
    public javax.swing.JButton __GUARDAR_TABLA_LIBRO;
    public javax.swing.JButton __GUARDAR_TABLA_NOTA;
    public javax.swing.JButton __LIMPIAR_ARTICULO;
    public javax.swing.JButton __LIMPIAR_LIBRO;
    public javax.swing.JButton __LIMPIAR_NOTA;
    public javax.swing.JButton __MODIFICAR_ARTICULO;
    public javax.swing.JButton __MODIFICAR_LIBRO;
    public javax.swing.JButton __MODIFICAR_NOTA;
    public javax.swing.JButton __NUEVO_ARTICULO;
    public javax.swing.JButton __NUEVO_LIBRO;
    public javax.swing.JButton __VOLVER_ARTICULO;
    public javax.swing.JButton __VOLVER_LIBRO;
    public javax.swing.JButton __VOLVER_NOTA;
    public javax.swing.JTable __tabla_articulos;
    public javax.swing.JTable __tabla_libros;
    public javax.swing.JTable __tabla_notas;
    public javax.swing.JLabel actualUsrArticulo;
    public javax.swing.JLabel actualUsrLibro;
    public javax.swing.JLabel actualUsrNota;
    public javax.swing.JFormattedTextField anioArticuloFormatedBox;
    public javax.swing.JFormattedTextField anioLibroFormatedBox;
    public javax.swing.JPanel articuloPanel;
    public javax.swing.JTextField autorArticuloBox;
    public javax.swing.JTextField autorLibroBox;
    public javax.swing.JTextField busquedaArticuloBox;
    public javax.swing.JTextField busquedaLibroBox;
    public javax.swing.JTextField busquedaNotaBox;
    public javax.swing.JTextArea contenidoNotaArea;
    public javax.swing.JTextField editorialLibroBox;
    public javax.swing.JFormattedTextField idNotaBox;
    public static javax.swing.JTextField isbn1LibroBox;
    public static javax.swing.JTextField isbn2LibroBox;
    public javax.swing.JCheckBox isbnCheckBox;
    public javax.swing.JFormattedTextField isbnNotaBox;
    public static javax.swing.JTextField issn1ArticuloBox;
    public static javax.swing.JTextField issn2ArticuloBox;
    public javax.swing.JCheckBox issnCheckBox;
    public javax.swing.JFormattedTextField issnNotaBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JPanel libroPanel;
    public javax.swing.JFormattedTextField mesArticuloFormatedBox;
    public javax.swing.JFormattedTextField nPaginasLibroFormatedBox;
    public javax.swing.JPanel notaPanel;
    public javax.swing.JFormattedTextField pagFinArticuloFormatedBox;
    public javax.swing.JFormattedTextField pagIniArticuloFormatedBox;
    public javax.swing.JTextField revistaArticuloBox;
    public javax.swing.JTextField temaNotaBox;
    public javax.swing.JTextField tituloArticuloBox;
    public javax.swing.JTextField tituloLibroBox;
    // End of variables declaration//GEN-END:variables
}
